name: esalesapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^3.0.0 #baru
  google_fonts: ^6.1.0 #baru
  flutter_staggered_animations: ^1.1.1 #baru
  universal_html: ^2.0.8 #baru
  encrypt: ^5.0.1 #baru

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  accordion: ^2.6.0
  animated_tree_view: ^2.3.0
  checkbox_grouped: ^2.0.0
  cupertino_icons: ^1.0.6
  connectivity_plus: ^6.0.2
  const_date_time: ^1.1.0
  collection: ^1.18.0
  cross_file: ^0.3.4+1
  dropdown_search: ^6.0.1
  date_field: ^6.0.3+1
  dio: ^5.4.0
  equatable: ^2.0.3
  flutter_chat_ui: ^1.6.12
  file_picker: ^8.0.0+1
  flex_color_scheme: ^8.0.2
  flutter_chat_types: ^3.6.2
  flutter_file_downloader: ^1.2.1
  flutter_speed_dial: ^7.0.0
  flutter_slidable: ^3.1.2
  flutter_launcher_icons: ^0.14.2
  flutter_svg: ^2.0.0+1
  flutter_bloc: ^8.0.0
  foundation: ^0.0.5
  grouped_list: ^6.0.0
  http: ^1.2.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  image: any
  jiffy: ^6.3.0
  mime: ^2.0.0
  meta: ^1.10.0
  open_filex: ^4.6.0
  percent_indicator: ^4.0.1
  path: ^1.9.0
  permission_handler: ^11.3.1
#  path_provider: ^2.0.11
  path_provider: ^2.0.14 #new
  sqflite: ^2.3.1  
  string_validator: ^1.0.2
  syncfusion_flutter_calendar: ^29.1.35
  syncfusion_flutter_datagrid: ^29.1.35
  speech_to_text: ^7.0.0
  timelines_plus: ^1.0.3
  tab_container: ^3.5.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  google_fonts: ^6.1.0

flutter:
  uses-material-design: true
  assets:  
    - assets/images/
    - assets/images/month/
    - assets/icons/
    - packages/timezone/data/latest.tzf
    - assets/images/jps-image.png
    - assets/images/vector-1.png
    - assets/images/vector-2.png
    - assets/images/vector-3.png
    - assets/images/vector-4.png
    - assets/images/vector-5.png
    - assets/images/vector-6.png
    - assets/images/vector-7.png
    - assets/images/vector-8.png
    - assets/images/vector-9.png
    - assets/images/vector-10.png
    - assets/images/vector-11.png
    - assets/images/shape-bottom.svg
    - assets/images/vector-home.png
    - assets/images/vector-12.png
    - assets/images/vector-13.png
    - assets/images/vector-14.png
    - assets/images/vector-15.png
    - assets/images/logo-briefing.png
    - assets/images/logo-business.png
    - assets/images/logo-category.png
    - assets/images/logo-insurer.png
    - assets/images/logo-job.png
    - assets/images/logo-list.png
    - assets/images/logo-media.png
    - assets/images/logo-policy.png
    - assets/images/logo-project.png
    - assets/images/logo-soa.png
    - assets/images/logo-subordinate.png
    - assets/images/logo-tasks.png
    - assets/images/list-subordinate-task.png
    - assets/images/logo-calender.png
    - assets/images/logo-timeline.png
    - assets/images/logo-title.png
    - assets/images/logo-client.png
    - assets/images/logo-jabatan.png
    - assets/images/logo-customer.png
    - assets/images/logo-karyawan.png
    - assets/images/logo-project-tree.png
    - assets/images/logo-support.png
    - assets/images/logo-password.png
    - assets/images/logo-password-change.png
  fonts:
    - family: HeeboBold
      fonts:
        - asset: assets/fonts/Heebo-Bold.ttf
    - family: HeeboMedium
      fonts:
        - asset: assets/fonts/Heebo-Medium.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf  

flutter_launcher_icons:
  image_path: "assets/images/logo_launcher.png"
  android: true
  ios: true  
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  min_sdk_android: 21 # android min sdk min:16, default 21